export const topicMap: Record<string, string> = {
  "Computation": "../data/lecture1.pdf",
  "Algorithms": "../data/lecture1.pdf",
  "Problem Solving": "../data/lecture1.pdf",
  "Conditionals": "../data/lecture2.pdf",
  "Loops": "../data/lecture2.pdf",
  "control flow": "../data/lecture2.pdf",
  "String Manipulation": "../data/lecture3.pdf",
  "Guess and Check": "../data/lecture3.pdf",
  "Approximation" : "../data/lecture3.pdf",
  "Bisection Search": "../data/lecture3.pdf",
  "Decomposition": "../data/lecture4.pdf",
  "Abstraction" : "../data/lecture4.pdf",
  "Functions": "../data/lecture4.pdf",
  "Tuples" : "../data/lecture5.pdf",
  "Lists": "../data/lecture5.pdf",
  "Aliasing" : "../data/lecture5.pdf",
  "Mutability": "../data/lecture5.pdf",
  "Cloning" : "../data/lecture5.pdf",
  "Recursion": "../data/lecture6.pdf",
  "Dictionaries": "../data/lecture6.pdf",
  "Testing" : "../data/lecture7.pdf",
  "Debugging": "../data/lecture7.pdf",
  "Exceptions": "../data/lecture7.pdf",
  "Assertions": "../data/lecture7.pdf",
  "Classes" : "../data/lecture8.pdf",
  "OOP" : "../data/lecture8.pdf",
  "Encapsulation": "../data/lecture8.pdf",
  "Inheritance": "../data/lecture9.pdf",
  "Subclasses": "../data/lecture9.pdf",
  "Class Hierarchies": "../data/lecture9.pdf",
  "Big-O Notation": "../data/lecture10.pdf",
  "Efficiency" : "../data/lecture10.pdf",
  "Search Algorithms": "../data/lecture12.pdf",
  "Space Complexity": "../data/lecture10.pdf",
  "Complexity Analysis": "../data/lecture11.pdf",
  "Sorting Algorithms": "../data/lecture12.pdf",
}